### ISSUE TITLE
Extraction not working: 7zip libraries not in classpath

### ISSUE THREAD

**Issue by SimDing** [jaymoulin/docker-jdownloader#120] opened 2022-07-06 14:33 UTC
**Output of `docker inspect jdownloader --format='{{index .Config.Labels.version}}'`:**

```
2.0.3-armhf
```

**Description**

I noticed that the extraction extension was not working. I was able to fix this by debugging my container and manually renaming the files `sevenzipjbinding1509.jar` and `sevenzipjbinding1509LinuxArmVersion.jar` to `sevenzipjbinding.jar` and `sevenzipjbindingLinuxArmVersion.jar` respectively. (According to the entries I found in `app/JDownloader.jar/classpath`.)

**Command line I used to start the container**

```
docker run -d --init --restart=always -v /xxx/xxx/xxx:/opt/JDownloader/Downloads -v /xxx/xxx/xxx/:/opt/JDownloader/app/cfg --name jdownloader -p 3129:3129 -e MYJD_DEVICE_NAME=xxx -v /etc/localtime:/etc/localtime:ro jaymoulin/jdownloader:2.0.3-armhf
```

**Steps to reproduce the issue:**

1. Start container
2. Wait for updates
3. Download archive

**Describe the results you received:**

Archive not extracted.

**Describe the results you expected:**

Archive extracted.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Provide some logs <strike>(`docker logs jdownloader`)</strike>**

app/JDownloader/logs/XXX/ExtractionExtension.log.0 (_prior to renaming_)
<details>
<pre>
------------------------Thread: 45:ExtractionExtension.log-----------------------
--ID:45TS:1657108524722-7/6/22, 11:55:24 AM -  [org.jdownloader.extensions.extraction.multi.Multi(checkLibraries)] -> Try LibIDs: [Linux-armhf-musl, Linux-armv7-musl, Linux-armv5, Linux-armv6, Linux-armv71, Linux-armpi, Linux-armpi2, Linux-arm2, Linux-arm, Linux-arm3]
--ID:45TS:1657108524723-7/6/22, 11:55:24 AM -  [org.jdownloader.extensions.extraction.multi.Multi(initLibrary)] -> LibID not found: Linux-armhf-musl
--ID:45TS:1657108524724-7/6/22, 11:55:24 AM -  [org.jdownloader.extensions.extraction.multi.Multi(initLibrary)] -> LibID not found: Linux-armv7-musl
--ID:45TS:1657108524725-7/6/22, 11:55:24 AM -  [org.jdownloader.extensions.extraction.multi.Multi(initLibrary)] -> LibID not found: Linux-armv5
--ID:45TS:1657108524725-7/6/22, 11:55:24 AM -  [org.jdownloader.extensions.extraction.multi.Multi(initLibrary)] -> LibID not found: Linux-armv6
--ID:45TS:1657108524726-7/6/22, 11:55:24 AM -  [org.jdownloader.extensions.extraction.multi.Multi(initLibrary)] -> LibID not found: Linux-armv71
--ID:45TS:1657108524727-7/6/22, 11:55:24 AM -  [org.jdownloader.extensions.extraction.multi.Multi(initLibrary)] -> LibID not found: Linux-armpi
--ID:45TS:1657108524728-7/6/22, 11:55:24 AM -  [org.jdownloader.extensions.extraction.multi.Multi(initLibrary)] -> LibID not found: Linux-armpi2
--ID:45TS:1657108524729-7/6/22, 11:55:24 AM -  [org.jdownloader.extensions.extraction.multi.Multi(initLibrary)] -> LibID not found: Linux-arm2
--ID:45TS:1657108524729-7/6/22, 11:55:24 AM -  [org.jdownloader.extensions.extraction.multi.Multi(initLibrary)] -> LibID not found: Linux-arm
--ID:45TS:1657108524730-7/6/22, 11:55:24 AM -  [org.jdownloader.extensions.extraction.multi.Multi(initLibrary)] -> LibID not found: Linux-arm3
--ID:45TS:1657108524741-7/6/22, 11:55:24 AM -  [] -> Exception thrown at org.jdownloader.extensions.extraction.multi.Multi.checkLibraries(Multi.java:237):
net.sf.sevenzipjbinding.SevenZipNativeInitializationException: Can not find 7-Zip-JBinding platform property file /sevenzipjbinding-platforms.properties. Make sure the 'sevenzipjbinding-<Platform>.jar' file is on the class path or consider initializing SevenZipJBinding manualy using one of the offered initialization methods: 'net.sf.sevenzipjbinding.SevenZip.init*()'
	at net.sf.sevenzipjbinding.SevenZip.getPlatformList(SevenZip.java:284)
	at org.jdownloader.extensions.extraction.multi.Multi.checkLibraries(Multi.java:235)
	at org.jdownloader.extensions.extraction.multi.Multi.hasLibrarySupport(Multi.java:418)
	at org.jdownloader.extensions.extraction.multi.Multi.isAvailable(Multi.java:440)
	at org.jdownloader.extensions.extraction.ExtractionExtension.lazyInitOnceOnStart(ExtractionExtension.java:473)
	at org.jdownloader.extensions.extraction.ExtractionExtension.start(ExtractionExtension.java:397)
	at org.jdownloader.extensions.AbstractExtension.setEnabled(AbstractExtension.java:79)
	at org.jdownloader.extensions.AbstractExtension.init(AbstractExtension.java:319)
	at org.jdownloader.extensions.LazyExtension.init(LazyExtension.java:210)
	at org.jdownloader.extensions.ExtensionController.loadFromCache(ExtensionController.java:250)
	at org.jdownloader.extensions.ExtensionController.init(ExtensionController.java:141)
	at jd.SecondLevelLaunch$9$1$2.run(SecondLevelLaunch.java:758)

--ID:45TS:1657108524760-7/6/22, 11:55:24 AM -  [org.jdownloader.extensions.extraction.multi.Multi(isAvailable)] -> Unsupported SevenZipJBinding|Version=16.02-2.01|CPU_ARCH=ARM|OS_FAM=LINUX|OS=ALPINE|64Bit_JVM=false|64Bit_ARCH=false|HW:RaspberryPI|Type:4B|MemorySize:GB_4|Manufacturer:SONY_UK|Processor:BCM2711|Raw:c03111
--ID:45TS:1657108524761-7/6/22, 11:55:24 AM -  [org.jdownloader.extensions.extraction.ExtractionExtension(lazyInitOnceOnStart)] -> Extractor org.jdownloader.extensions.extraction.multi.Multi plugin could not be initialized
--ID:45TS:1657108524767-7/6/22, 11:55:24 AM -  [org.jdownloader.extensions.AbstractExtension(init)] -> Init Duration: 455
</pre>
</details>

app/JDownloader/logs/XXX/ExtractionExtension.log.0 (_after renaming_)
<details>
<pre>
------------------------Thread: 45:ExtractionExtension.log-----------------------
--ID:45TS:1657114625183-7/6/22, 1:37:05 PM -  [org.jdownloader.extensions.extraction.multi.Multi(checkLibraries)] -> Try LibIDs: [Linux-armv71, Linux-armhf-musl, Linux-armv7-musl, Linux-armv5, Linux-armv6, Linux-armpi, Linux-armpi2, Linux-arm2, Linux-arm, Linux-arm3]
--ID:45TS:1657114625192-7/6/22, 1:37:05 PM -  [org.jdownloader.extensions.extraction.multi.Multi(initLibrary)] -> LibID found: Linux-armv71
--ID:45TS:1657114625201-7/6/22, 1:37:05 PM -  [org.jdownloader.extensions.extraction.multi.Multi(initLibrary)] -> Try LibID(Linux-armv71) Path: /opt/JDownloader/app/tmp/7zip->true
--ID:45TS:1657114625328-7/6/22, 1:37:05 PM -  [org.jdownloader.extensions.extraction.multi.Multi(isAvailable)] -> Supported SevenZipJBinding|LibID=Linux-armv71|Version=16.02-2.01|RAR5=true|CPU_ARCH=ARM|OS_FAM=LINUX|OS=ALPINE|64Bit_JVM=false|64Bit_ARCH=false|HW:RaspberryPI|Type:4B|MemorySize:GB_4|Manufacturer:SONY_UK|Processor:BCM2711|Raw:c03111
--ID:45TS:1657114625333-7/6/22, 1:37:05 PM -  [org.jdownloader.extensions.AbstractExtension(init)] -> Init Duration: 459
------------------------Thread: 257:ExtractionExtension.log-----------------------
--ID:257TS:1657114659124-7/6/22, 1:37:39 PM -  [org.jdownloader.extensions.extraction.ExtractionExtension(onNewArchive)] -> Archive:sample-zip-file
Type:ZIP_SINGLE
Existing:DownloadLink:/opt/JDownloader/Downloads/sample-zip-file.zip|Complete:true
Complete:true
--ID:257TS:1657114659125-7/6/22, 1:37:39 PM -  [org.jdownloader.extensions.extraction.ExtractionExtension(onNewArchive)] -> Caller:Thread[Download: sample-zip-file.zip_http links,1,]|Archive:sample-zip-file|Complete|Size:1
--ID:257TS:1657114659140-7/6/22, 1:37:39 PM -  [org.jdownloader.extensions.extraction.ExtractionExtension(addToQueue)] -> Archive:sample-zip-file
Type:ZIP_SINGLE
Existing:DownloadLink:/opt/JDownloader/Downloads/sample-zip-file.zip|Complete:true
Complete:true
</pre>
</details>

**Comment by SimDing** [comment] 2022-07-15 08:47
Sorry I don't understand what kind of link you want. I'm using the container on a raspberry pi in my local network and observed this behaviour after using the above command. I assumed the libraries were renamed in a newer jdownloader version. What kind of link do you mean?

**Comment by jaymoulin** [comment] 2022-07-15 14:36
I'm asking for the link you try to download. As explained in my previous message, I'm using this version and I can't reproduce this bug. Zip are extracted without any need for renaming plugins and you seem to be the only user with this issue.

**Comment by ilteoood** [comment] 2022-08-06 19:06
Hi @jaymoulin,
I've the same issue.

Previously it was working, but when I created a new container using the same image extraction stopped working.

**Comment by jaymoulin** [comment] 2022-08-06 21:07
Still waiting for information though. I wonder why I didn't close this issue earlier...

**Comment by ilteoood** [comment] 2022-08-06 21:14
This is the first rar sample found online:
https://workupload.com/file/zMR4vIPW

![Screenshot_20220806_231323](https://user-images.githubusercontent.com/6383527/183266238-ad35fe98-db8b-484b-974a-5985f350cfb5.jpg)

Jdownloader just downloads it, without extracting

![Screenshot_20220806_231124_edit_316481113383478](https://user-images.githubusercontent.com/6383527/183266245-d509a66e-7687-4988-b5ed-9953dcc127e7.jpg)

Unrar is able to extract it without problems.

**Comment by jaymoulin** [comment] 2022-08-06 21:23
Thank you @ilteoood for your link, I'll have a look

**Comment by jaymoulin** [comment] 2022-08-06 22:01
```shell
$> docker inspect jdownloader --format='{{index .Config.Labels.version}}'
2.0.3-armhf
$> docker images jaymoulin/jdownloader
REPOSITORY              TAG       IMAGE ID       CREATED        SIZE
jaymoulin/jdownloader   latest    80267091add3   6 months ago   262MB
$> uname -m
armv7l
```

```
jdownloader_1   |
jdownloader_1   | THREAD: 42
jdownloader_1   | 42|Log.L.log 8/6/22, 11:58:00 PM - FINEST [ org.appwork.loggingv3.LogV3(finest) ] -> jd.controlling.downloadcontroller.DownloadWatchDog@1504847 State changed IDLE--1(20522513) -> RUNNING--1(7842042)
jdownloader_1   |
jdownloader_1   | THREAD: 298
jdownloader_1   | 298|Log.L.log 8/6/22, 11:58:00 PM - FINER [ org.appwork.loggingv3.LogV3(finer) ] -> Init StorageHandler for Interface:org.jdownloader.controlling.hosterrule.HosterRuleConfig|Path:null
jdownloader_1   |
jdownloader_1   | THREAD: 323
jdownloader_1   | 323|Log.L.log 8/6/22, 11:58:04 PM - FINER [ org.appwork.loggingv3.LogV3(finer) ] -> Read Config(File): /opt/JDownloader/app/cfg/org.jdownloader.extensions.extraction.ExtractionExtension.blacklistpatterns.json
jdownloader_1   | 323|Log.L.log 8/6/22, 11:58:04 PM - FINER [ org.appwork.loggingv3.LogV3(finer) ] -> Read Config(File): /opt/JDownloader/app/cfg/org.jdownloader.extensions.extraction.ExtractionExtension.deepextractionblacklistpatterns.json
jdownloader_1   |
jdownloader_1   | THREAD: 347
jdownloader_1   | 347|Log.L.log 8/6/22, 11:58:11 PM - FINEST [ org.appwork.loggingv3.LogV3(finest) ] -> jd.controlling.downloadcontroller.DownloadWatchDog@1504847 State changed RUNNING--1(7842042) -> STOPPING--1(15576948)
jdownloader_1   | 347|Log.L.log 8/6/22, 11:58:11 PM - FINEST [ org.appwork.loggingv3.LogV3(finest) ] -> jd.controlling.downloadcontroller.DownloadWatchDog@1504847 State changed STOPPING--1(15576948) -> STOPPED_STATE--1(1426436)
```

Still no problem for extraction here. Are you sure to be running the docker image on an arm32v6 architecture?

**Comment by ilteoood** [comment] 2022-08-06 22:31
Yes I did and everything was right until the last 2 weeks, I've used this image for more than a year.

If I filter the logs for the "zip" word, I see the following sentences:

cp: can't create '/opt/JDownloader/app/libs/sevenzipjbinding1509.jar': No such file or directory
cp: can't create '/opt/JDownloader/app/libs/sevenzipjbinding1509LinuxArmVersion.jar': No such file or directory

And, at the end:
SevenZipJBinding: null

[_jdownloader-jdownloader-1_logs.txt](https://github.com/jaymoulin/docker-jdownloader/files/9275854/_jdownloader-jdownloader-1_logs.txt)

Here is the full log

**Comment by jaymoulin** [comment] 2022-08-06 23:01
The image is 6 months old. 
If the bug appeared 2 weeks ago, it does not have to do with the docker image but either with JDownloader or your configuration. 

As I can't reproduce the bug with the exact same configuration, I'm pretty sure it has something to do with your configuration. 

> If I filter the logs for the "zip" word, I see the following sentences:
> 
> cp: can't create '/opt/JDownloader/app/libs/sevenzipjbinding1509.jar': No such file or directory cp: can't create '/opt/JDownloader/app/libs/sevenzipjbinding1509LinuxArmVersion.jar': No such file or directory


This indicates you may have a permission error
Please check your mounted folders and permissions

**Closed** 2022-08-09 13:15 UTC
Labels: invalid, question
