### ISSUE TITLE
RAR5 - Jdownloader and Docker

### ISSUE THREAD

**Issue by Loik419** [jaymoulin/docker-jdownloader#29] opened 2019-05-24 16:14 UTC
Hello,

Jdownloader in native still does not take the RAR5.

However, a file has been created to address this problem:

Linux (64Bit only, Intel / AMD) Updated on 07.10.2016 because of wrong file naming!
mega.nz/#!eAtQ1LxL!vLbU9e9hWWc9QcfaNwwaiB3bbwlC4bOC7QchAUckF0g

which can be found at https://board.jdownloader.org/showthread.php?t=71069.

You have to put these files in the folder LIBS, but I can not find it under OMV4 and docker.

Do you know the position of the file? Or, is there a way to integrate its 2 files with the docker version?

(I also have the version of Jdownloader under windows and the files work very well).

Thank you in advance,

**Comment by jaymoulin** [comment] 2019-05-26 10:54
Duplicate of #10.
Also I need information to reproduce your specific problem (All needed information are in the template when you create an issue)

**Closed by jaymoulin** 2019-05-26 10:54 UTC
Labels: invalid
